Set DATASET_URL default and enable to run out of the box
elyra-ai/examples pull request #24
Opened 2020-10-22 16:34 UTC by lresende

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2020-10-23 00:40 UTC, yil532 commented
@lresende @ptitzler Should dataset link be https://dax-cdn.cdn.appdomain.cloud/dax-noaa-weather-data-jfk-airport/1.1.4/noaa-weather-data-jfk-airport.tar.gz ?

2020-10-23 13:34 UTC, ptitzler requested changes
Would be curious to understand how hardwiring the data set URL helps, considering that we are positioning `load_data` as a generic download node for DAX data sets. It doesn't save the user any time or make things simpler
- the pipeline file already defines all required inputs
- if one wants to re-create the pipeline from scratch one still has to define the other dependencies

2020-10-23 13:34 UTC, ptitzler commented on pipelines/dax_noaa_weather_data/load_data.ipynb
> +    "data_file = os.getenv('DATASET_URL', 'https://dax-cdn.cdn.appdomain.cloud/dax-fashion-mnist/1.0.2/fashion-mnist.tar.gz')"
```suggestion
    "data_file = os.getenv('DATASET_URL', 'https://dax-cdn.cdn.appdomain.cloud/dax-noaa-weather-data-jfk-airport/1.1.4/noaa-weather-data-jfk-airport.tar.gz ')"
```

2020-10-29 03:54 UTC, lresende commented
> Would be curious to understand how hardwiring the data set URL helps, considering that we are positioning `load_data` as a generic download node for DAX data sets. It doesn't save the user any time or make things simpler
> 

I just want to make the notebook runnable by itself, if the user is not running via a pipeline.

2020-10-29 18:36 UTC, ptitzler approved these changes
LGTM

2020-11-09 18:28 UTC, merged